version: '3.8'

services:
  # Управляющие серверы
  da1:
    build: .
    environment:
      - NICK=dauvfnvkeo
      - IP_ADDR=10.5.11.139
      - ROLE=da
    volumes:
      - somevol:/status/dir-authorities
    networks:
      - tor-network

  da2:
    build: .
    environment:
      - NICK=daxunpfymo
      - IP_ADDR=10.5.99.44
      - ROLE=da
    networks:
      - tor-network

  da3:
    build: .
    environment:
      - NICK=dahgndngrb
      - IP_ADDR=10.5.179.14
      - ROLE=da
    networks:
      - tor-network

  # Реле
  relay1:
    build: .
    environment:
      - NICK=relaynzsilcfk
      - IP_ADDR=10.5.188.28
      - ROLE=relay
    networks:
      - tor-network

  relay2:
    build: .
    environment:
      - NICK=relayhctniqea
      - IP_ADDR=10.5.88.31
      - ROLE=relay
    networks:
      - tor-network

  relay3:
    build: .
    environment:
      - NICK=relayphruftoo
      - IP_ADDR=10.5.137.197
      - ROLE=relay
    networks:
      - tor-network

  relay4:
    build: .
    environment:
      - NICK=relaypsxaafiq
      - IP_ADDR=10.5.229.1
      - ROLE=relay
    networks:
      - tor-network

  relay5:
    build: .
    environment:
      - NICK=relayageofxuu
      - IP_ADDR=10.5.104.32
      - ROLE=relay
    networks:
      - tor-network

  # Выходные узлы
  exit1:
    build: .
    environment:
      - NICK=exitvbmpegsv
      - IP_ADDR=10.5.56.142
      - ROLE=exit
    networks:
      - tor-network

  exit2:
    build: .
    environment:
      - NICK=exitqmrbravr
      - IP_ADDR=10.5.242.11
      - ROLE=exit
    networks:
      - tor-network

  exit3:
    build: .
    environment:
      - NICK=exitwhitmyoo
      - IP_ADDR=10.5.82.75
      - ROLE=exit
    networks:
      - tor-network

  # Клиент
  client:
    build: .
    environment:
      - NICK=clientpdca
      - IP_ADDR=10.5.140.177
      - ROLE=client
    networks:
      - tor-network

  # сервис onion
  hs:
    build: .
    environment:
      - NICK=hsservice
      - IP_ADDR=10.5.108.221
      - ROLE=hs
    networks:
      - tor-network

networks:
  tor-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  somevol: