version: '3.8'

services:
  # Управляющие серверы
  da1:
    build: .
    environment:
      - NICK=dauvfnvkeo
      - IP_ADDR=10.5.11.139
      - ROLE=da
    volumes:
      - somevol:/shavol
    networks:
      tor-network:
        ipv4_address: 10.5.11.139

  da2:
    build: .
    environment:
      - NICK=daxunpfymo
      - IP_ADDR=10.5.99.44
      - ROLE=da
    volumes:
      - somevol:/shavol
    depends_on:
      - da1
    networks:
      tor-network:
        ipv4_address: 10.5.99.44

  da3:
    build: .
    environment:
      - NICK=dahgndngrb
      - IP_ADDR=10.5.179.14
      - ROLE=da
    volumes:
      - somevol:/shavol
    depends_on:
      - da2
    networks:
      tor-network:
        ipv4_address: 10.5.179.14

  # Реле
  relay1:
    build: .
    environment:
      - NICK=relaynzsilcfk
      - IP_ADDR=10.5.188.28
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - da3
    networks:
      tor-network:
        ipv4_address: 10.5.188.28

  relay2:
    build: .
    environment:
      - NICK=relayhctniqea
      - IP_ADDR=10.5.88.31
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - relay1
    networks:
      tor-network:
        ipv4_address: 10.5.88.31

  relay3:
    build: .
    environment:
      - NICK=relayphruftoo
      - IP_ADDR=10.5.137.197
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - relay2
    networks:
      tor-network:
        ipv4_address: 10.5.137.197

  relay4:
    build: .
    environment:
      - NICK=relaypsxaafiq
      - IP_ADDR=10.5.229.1
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - relay3
    networks:
      tor-network:
        ipv4_address: 10.5.229.1

  relay5:
    build: .
    environment:
      - NICK=relayageofxuu
      - IP_ADDR=10.5.104.32
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - relay4
    networks:
      tor-network:
        ipv4_address: 10.5.104.32

  # Выходные узлы
  exit1:
    build: .
    environment:
      - NICK=exitvbmpegsv
      - IP_ADDR=10.5.56.142
      - ROLE=exit
    volumes:
      - somevol:/shavol
    depends_on:
      - relay5
    networks:
      tor-network:
        ipv4_address: 10.5.56.142

  exit2:
    build: .
    environment:
      - NICK=exitqmrbravr
      - IP_ADDR=10.5.242.11
      - ROLE=exit
    volumes:
      - somevol:/shavol
    depends_on:
      - exit1
    networks:
      tor-network:
        ipv4_address: 10.5.242.11

  exit3:
    build: .
    environment:
      - NICK=exitwhitmyoo
      - IP_ADDR=10.5.82.75
      - ROLE=exit
    volumes:
      - somevol:/shavol
    depends_on:
      - exit2
    networks:
      tor-network:
        ipv4_address: 10.5.82.75

  # Клиент
  client:
    build: .
    environment:
      - NICK=clientpdca
      - IP_ADDR=10.5.140.177
      - ROLE=client
    volumes:
      - somevol:/shavol
    depends_on:
      - exit3
    networks:
      tor-network:
        ipv4_address: 10.5.140.177

  # Сервис onion
  hs:
    build: .
    environment:
      - NICK=hsservice
      - IP_ADDR=10.5.108.221
      - ROLE=hs
    depends_on:
      - client
    volumes:
      - somevol:/shavol
    networks:
      tor-network:
        ipv4_address: 10.5.108.221

networks:
  tor-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  somevol: