services:
  # Управляющие серверы
  da1:
    build: .
    environment:
      - NICK=da1
      - IP_ADDR=10.5.11.139
      - ROLE=da
    volumes:
      - somevol:/shavol
    networks:
      tor-network:
        ipv4_address: 10.5.11.139

  da2:
    build: .
    environment:
      - NICK=da2
      - IP_ADDR=10.5.99.44
      - ROLE=da
    volumes:
      - somevol:/shavol
    depends_on:
      - da1
    networks:
      tor-network:
        ipv4_address: 10.5.99.44

  da3:
    build: .
    environment:
      - NICK=da3
      - IP_ADDR=10.5.179.14
      - ROLE=da
    volumes:
      - somevol:/shavol
    depends_on:
      - da2
    networks:
      tor-network:
        ipv4_address: 10.5.179.14

  # Реле
  relay1:
    build: .
    environment:
      - NICK=relay1
      - IP_ADDR=10.5.188.28
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - da3
    networks:
      tor-network:
        ipv4_address: 10.5.188.28

  relay2:
    build: .
    environment:
      - NICK=relay2
      - IP_ADDR=10.5.88.31
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - relay1
    networks:
      tor-network:
        ipv4_address: 10.5.88.31

  relay3:
    build: .
    environment:
      - NICK=relay3
      - IP_ADDR=10.5.137.197
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - relay2
    networks:
      tor-network:
        ipv4_address: 10.5.137.197

  relay4:
    build: .
    environment:
      - NICK=relay4
      - IP_ADDR=10.5.229.1
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - relay3
    networks:
      tor-network:
        ipv4_address: 10.5.229.1

  relay5:
    build: .
    environment:
      - NICK=relay5
      - IP_ADDR=10.5.104.32
      - ROLE=relay
    volumes:
      - somevol:/shavol
    depends_on:
      - relay4
    networks:
      tor-network:
        ipv4_address: 10.5.104.32

  # Выходные узлы
  exit1:
    build: .
    environment:
      - NICK=exit1
      - IP_ADDR=10.5.56.142
      - ROLE=exit
    volumes:
      - somevol:/shavol
    depends_on:
      - relay5
    networks:
      tor-network:
        ipv4_address: 10.5.56.142

  exit2:
    build: .
    environment:
      - NICK=exit2
      - IP_ADDR=10.5.242.11
      - ROLE=exit
    volumes:
      - somevol:/shavol
    depends_on:
      - exit1
    networks:
      tor-network:
        ipv4_address: 10.5.242.11

  exit3:
    build: .
    environment:
      - NICK=exit3
      - IP_ADDR=10.5.82.75
      - ROLE=exit
    volumes:
      - somevol:/shavol
    depends_on:
      - exit2
    networks:
      tor-network:
        ipv4_address: 10.5.82.75

  hs:
    build: .
    environment:
      - NICK=hsservice
      - IP_ADDR=10.5.108.221
      - ROLE=hs
      - HS_PORT=8070
      - SERVICE_IP=10.5.8.23
      - SERVICE_PORT=5000
    depends_on:
      - client
    volumes:
      - somevol:/shavol
    networks:
      tor-network:
        ipv4_address: 10.5.108.221
    
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    networks:
      tor-network:
        ipv4_address: 10.5.250.10

networks:
  tor-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  somevol:
  ovpn-data: